# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, '正常'), (0, '迟到'), (0, '旷课')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('record', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='area',
            field=models.IntegerField(choices=[(0, '北京校区'), (1, '上海校区'), (2, '广州校区')], default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '未报名'), (0, '已报名'), (0, '老学员')], default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='stu_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Class'),
        ),
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='stu_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.Student'),
        ),
    ]
