# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
