# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '权限',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单'},
        ),
        migrations.AddField(
            model_name='authority',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Menu'),
        ),
    ]
