# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20170705_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='menu',
        ),
        migrations.AddField(
            model_name='authority',
            name='menu',
            field=models.ManyToManyField(related_name='menu', to='myadmin.Menu'),
        ),
    ]
