# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20170727_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单'},
        ),
    ]
