# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20170802_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
    ]
